lms/library/urls.py
from library import views
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

app_name = 'library'
urlpatterns = [

    path('registered', views.registered, name='registered'),
    path('', views.home, name='home'),
    path('signin/', views.UserFormView.as_view(), name='signin'),
    path('success/', views.sucess, name='success'),
    path('failed/', views.failed, name='failed'),
    path('login/', views.UserLoginFormView.as_view(), name='login'),
    path('book/', views.IndexView.as_view(), name='book'),
    path('detail/<int:pk>/', views.DetailViewUser.as_view(), name='detail'),
    path('detailuser/', views.Detailuser, name='detailuser'),
    path('search/', views.searchh, name='search'),
    path('book/issue/', views.IssueDetailView.as_view(), name='issuebook'),
    path('book/create/', views.BookCreate.as_view(), name='bookcreate'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='updatebook'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='deletebook'),
    path('book/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('book/<int:pk>/<int:userid>/', views.DetailView.as_view(), name='detail'),
    path('logout/', views.logoutr, name="logout"),
    path('issuedetail/<int:pk>/delete/', views.IssueDetailDelete.as_view(), name="issuedetaildelete"),
    path('results/', views.searchh, name='searching'),
    path('UserUpdate/<int:pk>/', views.UserUpdate.as_view(), name='UserUpdate'),
    path('issuelist/', views.issuelist, name='issuelist'),
    path('alluser/', views.alluser, name='alluser'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_ROOT=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_ROOT=settings.MEDIA_ROOT)

lms/lms/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('',include('library.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_ROOT=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_ROOT=settings.MEDIA_ROOT)

lms/library/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.contrib.postgres.fields import ArrayField
from datetime import datetime


class book(models.Model):
    bookimg = models.ImageField(upload_to='book_image',blank=True)
    title = models.CharField(max_length=120)
    subject = models.CharField(max_length=120)
    authorname = models.CharField(max_length=120)
    price = models.FloatField()
    edition=models.CharField(max_length=50)

    def get_absolute_url(self):
        return reverse('library:book')

    def __str__(self):
        return self.title + "  " + self.authorname


class User(AbstractUser):
    dfee = models.IntegerField(default=0)
    listbook = ArrayField(models.PositiveIntegerField(),null=True)

    def get_absolute_url(self):
        return reverse('library:detailuser')


class issuedetail(models.Model):
    Book = models.IntegerField()
    userid = models.PositiveIntegerField()
    issuedate = models.DateField(default=datetime.now().date(),blank=True)

    def get_absolute_url(self):
        return reverse('library:success')


class returndetail(models.Model):
    Issuedetail = models.ForeignKey(issuedetail,on_delete=models.CASCADE)
    returndetail = models.DateField()
    duefee = models.FloatField()



lms/library/forms.py
from django.contrib.auth import get_user_model
from django import forms
from . models import issuedetail
User=get_user_model()


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model=User
        fields=['username','first_name','last_name','email','password']


class UserLoginForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model=User
        fields=['username','password']


class IssueDetailForm(forms.ModelForm):

    class Meta:
        model = issuedetail
        fields = ['Book']

lms/library/views.py
from django import http
from datetime import timedelta
from .models import book, issuedetail, returndetail
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views.generic import View
from .forms import UserForm, UserLoginForm, IssueDetailForm
from django.contrib.auth import get_user_model
from django.shortcuts import render
from simple_search import search_filter
from datetime import datetime, date

User = get_user_model()


def home(request):
    return render(request, 'library/home.html')


class UserFormView(View):
    form_class = UserForm
    template_name = 'library/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user.listbook = []
            return redirect('library:registered')

        return render(request, self.template_name, {'form': form})


def registered(request):
    return render(request, 'library/registered.html')


class UserLoginFormView(View):
    form_class = UserLoginForm
    template_name = 'library/login_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
            return redirect('library:book')

        return render(request, self.template_name, {'form': form})


class UserUpdate(UpdateView):
    model = User
    fields = ['username', 'first_name', 'last_name', 'email']


class BookCreate(CreateView):
    model = book
    fields = ['title', 'subject', 'authorname', 'price', 'edition', 'bookimg']


class BookUpdate(UpdateView):
    model = book
    fields = ['title', 'subject', 'authorname', 'price', 'edition', 'bookimg']


class BookDelete(DeleteView):
    model = book
    template_name = 'library/delete.html'
    context_object_name = 'books'
    success_url = reverse_lazy('library:book')


class IndexView(generic.ListView):
    template_name = 'library/book.html'
    context_object_name = 'allbook'

    def get_queryset(self):
        return book.objects.all()


class DetailViewUser(generic.DetailView):
    model = User
    template_name = 'library/detailuser.html'


class DetailView(generic.DetailView):
    model = book
    template_name = 'library/detail.html'


def searchh(request):
    search_fields = ['title', 'subject', 'edition', 'authorname']
    query = request.GET['q']
    posts = book.objects.filter(search_filter(search_fields, query))

    return render(request, 'library/result.html', {'posts': posts})


class IssueDetailView(View):
    form_class = IssueDetailForm
    template_name = 'library/issuedetail_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        Book = request.POST.get('Book')
        issuedate = date.today()
        userid = request.user.id
        p1 = issuedetail(Book=Book, issuedate=issuedate, userid=userid)
        allbook = book.objects.filter(id=Book)
        if len(allbook) > 0:
            # User.listbook.append(Book)
            p1.save()
            return redirect('library:success')
        else:
            return redirect('library:failed')

        return render(request, self.template_name, {'form': form})


def sucess(request):
    return render(request, 'library/success.html')


def failed(request):
    return render(request, 'library/failed.html')


def detailview(request):
    allissues = issuedetail.objects.filter(userid=User.pk)
    if len(allissues) > 0:
        return render(request, 'library:detailuser')
    else:
        return render(request, 'library:Noissues')


def logoutr(request):
    logout(request)
    return redirect('library:home')


def Detailuser(request):
    issue = issuedetail.objects.filter(userid=request.user.id)
    return render(request, 'library/detailuser.html', {'issue': issue})


def fine(issuepk):
    t = issuedetail.objects.filter(id=issuepk)
    for M in t:
        delta = date.today() - M.issuedate
        if delta.days > 7:
            User.dfee += 5 * (7 - delta.days)
            User.save()


class IssueDetailDelete(DeleteView):
    model = issuedetail
    template_name = 'library/return.html'
    context_object_name = 'returnbook'

    def delete(self, request, *args, **kwargs):
        issued = self.get_object()
        issuepk = issued.pk
        fine(issuepk)
        issued.delete()
        success_url = reverse_lazy('library:detailuser')
        return render(request,'library/detailuser.html')

def issuelist(request):
    issue = issuedetail.objects.filter()
    return render(request, 'library/issuelist.html', {'issue': issue})


def alluser(request):
    AllUser = User.objects.all()
    return render(request, 'library/alluser.html', {'AllUser': AllUser})

lms/library/templates/library/book.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>book</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


    <meta charset="UTF-8">
    <style>   table{
    width:100%;
    }
    table ,th ,td{
    border:1px solid black;
    border-collapse:collapse;
    background-color: #ddd;
    }
    th,tp{
    padding:15px;
    text-align:left;
    }

    </style>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <a class="navbar-brand" href="{%url 'library:home'%}">
            <img src="{% static 'library/image/book.jpg' %}" width="70" height="50" alt="">
        </a>
        <a class="navbar-brand" href="{%url 'library:home'%}">Library Management System</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link " href="{%url 'library:home'%}">Home </a>
                {% if not user.is_authenticated %}
                <a class="nav-item nav-link " href="{%url 'library:signin'%}">Sign-In </a>
                <a class="nav-item nav-link" href="{%url 'library:login'%}">Login</a>
                {% else %}
                <a class="nav-item nav-link" href="{%url 'library:detailuser'%}">{{user.username}}</a>
                <a class="nav-item nav-link active" href="{% url 'library:book'%}">Books</a>
                {% if user.is_superuser %}
                <a class="nav-item nav-link" href="{% url 'library:issuelist'%}">Issue Details</a>
                <a class="nav-item nav-link" href="{% url 'library:alluser'%}">User Details</a>
                {% endif %}
                <a class="nav-item nav-link" href="{% url 'library:logout'%}">Logout</a>
                {% endif %}


            </div>
        </div>
        <form method="get" action="/results/" class="navbar-form pull-right">
            <input type="text" id="searchBox" class="input-medium search-query" name="q" placeholder="Search">
            <input type="submit" class="btn" value="Search">
        </form>

    </div>
</nav>
{% if user.is_authenticated %}
<center><h2>Books</h2></center>
{% if allbook|length > 0%}
<center>
{% for books in allbook %}
<div class="card" style="width: 18rem;">
    <img src="{% static 'library/image/book.jpg' %}" alt="Card image cap" style="width:100%">
    <div class="card-body">
        <h5 class="card-title">Book ID: {{books.pk}}</h5>
        <h5 class="card-title">Title: {{books.title}}</h5>
        <h6 class="card-title">Author: {{books.authorname}}</h6>

        <a href="{% url 'library:detail' books.id%}" class="btn btn-primary">Detail</a>
        {% if user.is_superuser%}
        <a href="{% url 'library:updatebook' books.id%}" class="btn btn-primary">Update</a>
        <a href="{% url 'library:deletebook' books.id%}" class="btn btn-primary">Delete</a>
        {% endif %}
    </div>
</div>
{% endfor %}
</center>
{% else %}
<h2>
    <center>No book available</center>
</h2>

{% endif %}
{% if user.is_superuser%}
<h3>
<a href="{% url 'library:bookcreate' %}">Add New Book</a>
</h3>
{% endif %}
{% else %}
<center>
<h3>You first need to login or Sign-in to access this page!!</h3>
</center>
    {% endif %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>

</body>
</html>

lms/library/templates/library/issuelist.html
{% load static%}
<!doctype html>
<html lang="en">
<style>   table{
    width:75%;
    }
    table ,th ,td{
    border:1px solid black;
    border-collapse:collapse;
    background-color: #ddd;
    }
    th,tp{
    padding:15px;
    text-align:left;
    }


</style>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


    <title>home!</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <a class="navbar-brand" href="{%url 'library:home'%}">
            <img src="{% static 'library/image/book.jpg' %}" width="70" height="50" alt="">
        </a>
        <a class="navbar-brand" href="{%url 'library:home'%}">Library Management System</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link " href="{%url 'library:home'%}">Home </a>
                {% if not user.is_authenticated %}
                <a class="nav-item nav-link " href="{%url 'library:signin'%}">Sign-In </a>
                <a class="nav-item nav-link" href="{%url 'library:login'%}">Login</a>
                {% else %}
                <a class="nav-item nav-link" href="{%url 'library:detailuser'%}">{{user.username}}</a>
                <a class="nav-item nav-link" href="{% url 'library:book'%}">Books</a>
                {% if user.is_superuser %}
                <a class="nav-item nav-link active" href="{% url 'library:issuelist'%}">Issue Details</a>
                <a class="nav-item nav-link" href="{% url 'library:alluser'%}">User Details</a>
                {% endif %}
                <a class="nav-item nav-link" href="{% url 'library:logout'%}">Logout</a>

                {% endif %}


            </div>
        </div>
        <form method="get" action="/results/" class="navbar-form pull-right">
            <input type="text" id="searchBox" class="input-medium search-query" name="q" placeholder="Search">
            <input type="submit" class="btn" value="Search">
        </form>

    </div>
</nav>
{% csrf_token %}
<center>
    {% if user.is_superuser%}
    <h2> Books Issued :</h2>

    <table>
        {% if issue|length > 0%}
        <tr>
            <th> Book Id</th>
            <th> Issue Date</th>
            <th> User Id</th>
            <th> Return/delete entry</th>
        </tr>
        {% for issued in issue %}
        <tr>
            <th>{{issued.Book}}</th>
            <th>{{issued.issuedate}}</th>
            <th>{{issued.userid}}</th>
            <th><a href="{% url 'library:issuedetaildelete' issued.id %}">return book</a></th>
        </tr>
        {% endfor %}
        {% else %}
        <h2> no book issued yet!!</h2>
        {% endif %}
    </table>
    {% else %}
    <h2>You are not authorized to see the content!! login as an admin!!</h2>
    {% endif %}

</center>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

lms/library/templates/library/login_form.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Login </title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


    <meta charset="UTF-8">
    <style>   table{
    width:100%;
    }
    table ,th ,td{
    border:1px solid black;
    border-collapse:collapse;
    }
    th,tp{
    padding:15px;
    text-align:left;
    }



    </style>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <a class="navbar-brand" href="{%url 'library:home'%}">
            <img src="{% static 'library/image/book.jpg' %}" width="70" height="50" alt="">
        </a>
        <a class="navbar-brand" href="{%url 'library:home'%}">Library Management System</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link " href="{%url 'library:home'%}">Home </a>
                {% if not user.is_authenticated %}
                <a class="nav-item nav-link " href="{%url 'library:signin'%}">Sign-In </a>
                <a class="nav-item nav-link active" href="{%url 'library:login'%}">Login</a>
                {% else %}
                <a class="nav-item nav-link" href="{%url 'library:detailuser'%}">{{user.username}}</a>
                <a class="nav-item nav-link" href="{% url 'library:book'%}">Books</a>
                {% if user.is_superuser %}
                <a class="nav-item nav-link" href="{% url 'library:issuelist'%}">Issue Details</a>
                <a class="nav-item nav-link" href="{% url 'library:alluser'%}">User Details</a>
                {% endif %}
                <a class="nav-item nav-link" href="{% url 'library:logout'%}">Logout</a>
                {% endif %}


            </div>
        </div>
        <form method="get" action="/results/" class="navbar-form pull-right">
            <input type="text" id="searchBox" class="input-medium search-query" name="q" placeholder="Search">
            <input type="submit" class="btn" value="Search">
        </form>
    </div>
</nav>
<center>
    <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% if not user.is_authenticated %}
        <h1>
            <center>login</center>
        </h1>
        {% include 'library/form-template.html'%}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">
                    Submit
                </button>
            </div>
        </div>
        {% else %}
        <h2>{{user.username}},you are already logged in!!</h2>
</center>
{% endif %}
</body>
</html>

lms/library/templates/library/result.html
<!doctype html>
{% load static%}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


    <title>Search Result</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <a class="navbar-brand" href="{%url 'library:home'%}">
            <img src="{% static 'library/image/book.jpg' %}" width="70" height="50" alt="">
        </a>
        <a class="navbar-brand" href="{%url 'library:home'%}">Library Management System</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link " href="{%url 'library:home'%}">Home </a>
                {% if not user.is_authenticated %}
                <a class="nav-item nav-link " href="{%url 'library:signin'%}">Sign-In </a>
                <a class="nav-item nav-link" href="{%url 'library:login'%}">Login</a>
                {% else %}
                <a class="nav-item nav-link" href="{%url 'library:detailuser'%}">{{user.username}}</a>
                <a class="nav-item nav-link" href="{% url 'library:book'%}">Books</a>
                {% if user.is_superuser %}
                <a class="nav-item nav-link" href="{% url 'library:issuelist'%}">Issue Details</a>
                <a class="nav-item nav-link" href="{% url 'library:alluser'%}">User Details</a>
                {% endif %}
                <a class="nav-item nav-link" href="{% url 'library:logout'%}">Logout</a>
                {% endif %}


            </div>
        </div>
        <form method="get" action="/results/" class="navbar-form pull-right">
            <input type="text" id="searchBox" class="input-medium search-query" name="q" placeholder="Search">
            <input type="submit" class="btn" value="Search">
        </form>
    </div>
</nav>
{% csrf_token %}
<center>
    {% if user.is_authenticated%}
    <h1>Search Result :</h1>
    {% if posts|length > 0 %}
    {% for books in posts %}
    <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{% static 'library/image/book.jpg' %}" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title">{{books.pk}}</h5>
            <h5 class="card-title">{{books.title}}</h5>
            <h6 class="card-title">{{books.authorname}}</h6>
            <br>
            <a href="{% url 'library:detail' books.id%}" class="btn btn-primary">Detail</a>
            {% if user.is_superuser%}
            <br>
            <a href="{% url 'library:updatebook' books.id%}" class="btn btn-primary">update</a><br>
            <a href="{% url 'library:deletebook' books.id%}" class="btn btn-primary">Delete</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    {% else %}
    <h3> No such Book Found!!</h3>
    {% endif %}
    {% else %}
    <h3>You have to login or sign-in first!!</h3>
    {% endif %}
</center>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>